### ISSUE TITLE
集成PicGO以及图床

### ISSUE THREAD

**Issue by terwer** [terwer/src-sy-post-publisher#132]
集成PicGO，可直接粘贴图片自动上传。旧文档的非图床图片，在发布时候使用PicGO上传然后再发布

**Comment by mohuishou** [comment]
picgo 应该不支持浏览器使用，思源挂件块是一个纯 web 页面，可能会有问题

**Comment by terwer** [comment]
> picgo 应该不支持浏览器使用，思源挂件块是一个纯 web 页面，可能会有问题

支持的，思源挂件不是简单的嵌套Web页面，是可以调用electron的fetch请求的，这个与浏览器的fetch不同，可以做很多事情，原理是是可行的，我会在近期完成这个特性。

**Comment by mohuishou** [comment]
> > picgo 应该不支持浏览器使用，思源挂件块是一个纯 web 页面，可能会有问题
> 
> 支持的，思源挂件不是简单的嵌套Web页面，是可以调用electron的fetch请求的，这个与浏览器的fetch不同，可以做很多事情，原理上是可行的，我会在近期完成这个特性。

可以试试，我之前测试过发现不行，最后用了 s3，picgo-core 应该用了一部分 node 的 api 所以引入会报错

**Comment by leolee9086** [comment]
> > > picgo 应该不支持浏览器使用，思源挂件块是一个纯 web 页面，可能会有问题
> > 
> > 
> > 支持的，思源挂件不是简单的嵌套Web页面，是可以调用electron的fetch请求的，这个与浏览器的fetch不同，可以做很多事情，原理上是可行的，我会在近期完成这个特性。
> 
> 可以试试，我之前测试过发现不行，最后用了 s3，picgo-core 应该用了一部分 node 的 api 所以引入会报错

可以引入，但是可能需要在主界面注入后端代码，主界面是有node环境的

**Comment by leolee9086** [comment]
https://ld246.com/article/1661673805368  之前写过一个比较糙的示例 ，这个是在主窗口执行的

**Comment by terwer** [comment]
我单独提取了一个项目：

https://github.com/terwer/sy-picgo
