### ISSUE TITLE
蹲最新版

### ISSUE THREAD

**Issue by tf2jaguar** [terwer/src-sy-post-publisher#141]
期待最新版，最好能出一个视频教程，方便不熟悉前端语法的人使用

**Comment by terwer** [comment]
感谢，文档这块一直准备更新，只是最近比较忙，下个版本发布会之前会出完整的文档。另外，下个版本将会加入革命性更新  Anki 记忆卡、Github pages等实用功能，感谢支持。

**Comment by terwer** [comment]
可关注 #142
