### ISSUE TITLE
完善帮助文档和视频教程

### ISSUE THREAD

**Issue by terwer** [terwer/src-sy-post-publisher#142]
完善文字文档和视频教程。
- [ ] v0.0.3 帮助文档
- [x] v0.1.0 帮助文档
- [ ] v1.0.0 帮助文档

**Comment by lfk2458** [comment]
如果需要完善帮助文档，需要提交到哪里？

**Comment by terwer** [comment]
> 如果需要完善帮助文档，需要提交到哪里？

我重新部署了一个文档站：https://github.com/terwer/docs-sy-post-publisher

稍后所有文档都会迁移到这里，可以在这个仓库贡献。
