### ISSUE TITLE
挂件版支持统一管理子目录所有文章

### ISSUE THREAD

**Issue by mohuishou** [terwer/src-sy-post-publisher#144]
每个文章都去引入这个挂件没有必要，相关配置统一管理就好

![](https://raw.githubusercontent.com/mohuishou/siyuan-sync-github/main/public/preview.png)

类似我写的这种使用方式，你的这个挂件适配的平台更多，但是也更复杂

**Comment by terwer** [comment]
统一管理已经实现，只是没有放开页面。
目前是浏览器插件版本会展示统一管理入口。挂件受限于使用方式所以这块屏蔽了。

关于统一有什么思路吗，挂件好像默认必须每个文章引用，单独的入口目前还不知道怎么支持。

![image](https://user-images.githubusercontent.com/3259282/201832929-eb39191f-b628-4060-901c-47a8734a1ffa.png)

![image](https://user-images.githubusercontent.com/3259282/201832961-f7428094-71cb-45b2-8d7c-993b56f67784.png)

**Comment by mohuishou** [comment]
类似下面的代码，挂件放在父文件，这个时候就可以拿到这个文件的 id，然后查询这个文件夹下的所有文档块就能拿到所有的文档了

https://github.com/mohuishou/siyuan-sync-github/blob/main/src/api/siyuan.ts#L90

**Comment by terwer** [comment]
> 类似下面的代码，挂件放在父文件，这个时候就可以拿到这个文件的 id，然后查询这个文件夹下的所有文档块就能拿到所有的文档了
> 
> https://github.com/mohuishou/siyuan-sync-github/blob/main/src/api/siyuan.ts#L90

感谢，我大致明白你的意思了，很好，我会在下版本加上这个功能。
