### ISSUE TITLE
可以支持发布到typecho吗？

### ISSUE THREAD

**Issue by OriOYue** [terwer/src-sy-post-publisher#148]
作者大大，可以支持一下发布到typecho吗？

**Comment by terwer** [comment]
感谢建议，新版会支持，请耐心等待。

**Comment by terwer** [comment]
看了一下，这个支持xmlrpc，目前我这个支持 metaweblog 协议，其实可以直接添加使用的，知识可能只能兼容有限的函数。完整支持后面再看吧。

**Comment by terwer** [comment]
请使用xmlrpc统一平台，不再适配。
