### ISSUE TITLE
在配置发布到语雀的时候，每次都提示API验证失败

### ISSUE THREAD

**Issue by lfk2458** [terwer/src-sy-post-publisher#307]
正确填写语雀的Token之后，并给了相应的权限之后，仍无法配置语雀。
![验证失败的截图](https://user-images.githubusercontent.com/45598770/210961521-5ddc87f6-ff6c-4fa1-a373-0f132e35e1ac.png)
![语雀Token的设置截图](https://user-images.githubusercontent.com/45598770/210961941-8a4c604d-78c0-4718-b4a7-6d2effe61953.png)

**Comment by terwer** [comment]
用户名是这里的 


这个用户名的意思是你的自定义路径，不是用户昵称哦，注意不带/，例如我的是 terwer


| |
youweics
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年01月6日 16:31 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [terwer/src-sy-post-publisher] 在配置发布到语雀的时候，每次都提示API验证失败 (Issue #307) |

正确填写语雀的Token之后，并给了相应的权限之后，仍无法配置语雀。

**Comment by terwer** [comment]
用户名是这里的

![](https://user-images.githubusercontent.com/3259282/210965703-35b6e3fb-2e77-43f5-b8c0-fd28590c63e0.png)

这个用户名的意思是你的自定义路径，不是用户昵称哦，注意不带/，例如我的是 `terwer`  。目前我这里验证是正常的， 这个平台我一直在用。

**Comment by lfk2458** [comment]
好的，感谢。还有一个问题是服务开关中的Typeecho是否为Typecho博客？

**Comment by terwer** [comment]
> 好的，感谢。还有一个问题是服务开关中的Typeecho是否为Typecho博客？

是的，但是其实是通用 metaweblogAPI ，列出来是为了方便，暂时并没有进行特殊优化。有人已经使用过，目前来看基本使用应该是没问题。

**Comment by lfk2458** [comment]
好的，感谢。
