### ISSUE TITLE
发布到typeecho

### ISSUE THREAD

**Issue by lfk2458** [terwer/src-sy-post-publisher#308]
我想问一下发布到typeecho的API需要如何设置？

**Comment by terwer** [comment]
跟 Wordpress 是完全兼容的。

例如：
![image](https://user-images.githubusercontent.com/3259282/211013704-7ea61ab0-14f5-479b-8519-9a93a525fb37.png)

地址说明

```
http://<您的网址>/index.php/action/xmlrpc
# 例如：http://localhost:8080/index.php/action/xmlrpc
```

**Comment by lfk2458** [comment]
好的，谢谢解答。
