### ISSUE TITLE
在2.7.0版本中无法保存配置

### ISSUE THREAD

**Issue by GuangDai** [terwer/src-sy-post-publisher#350]
谢谢作者这个很棒的插件，解决了我很多的需求。

但是在2.7.0的siyuan Appimage(Linux)版本中，该插件无法保存配置。每次重启siyuan后都是这个样子。

![image](https://user-images.githubusercontent.com/59678726/214306250-6de67898-b07f-4519-b3e0-152db398a1b8.png)

![image](https://user-images.githubusercontent.com/59678726/214306306-181a9a22-5b99-4536-9195-b7410951ecb1.png)

请问是否是由于Appimage的特性？还是如何？

希望作者大大能抽时间解决一下这个bug，祝作者大大新年快乐！

**Comment by GuangDai** [comment]
![image](https://user-images.githubusercontent.com/59678726/214309645-38a5784a-4081-4250-8b23-0a69e44c1f7c.png)
这里出现的sy-p-cfg-v0.6.7.json是我导出到一个目录之后的。
这个是我索引全盘的结果，可以看到保存后，除了我导出的目录下，并没有一个对应的配置文件存在。

**Comment by terwer** [comment]
思源新版本2.6.2之后修改了数据存储机制导致，我在想办法按照这个方案修复，https://github.com/terwer/src-sy-post-publisher/issues/342 ，可关注这个issue。

**Comment by GuangDai** [comment]
> 思源新版本2.6.2之后修改了数据存储机制导致，我在想办法按照这个方案修复，#342 ，可关注这个issue。

好的，谢谢作者大大回复，作者大大辛苦了。再祝你新年快乐
