### ISSUE TITLE
Pic-Go 支持插件使用

### ISSUE THREAD

**Issue by SkysCrystal** [terwer/src-sy-post-publisher#378]
开发者大大您好！请问本 publisher 集成的 Pic-Go 是否支持插件， 如 alist， onemanager 等。

**Comment by terwer** [comment]
正好这个我也在研究之中，敬请期待！目前在完善配置图形界面这块。

**Comment by terwer** [comment]
重要变更：

为了支持插件，将PicGO配置文件移动到系统配置目录，具体为

```
Mac: ~/Library/Application Support/sy-picgo
Window: ~/AppData/Roaming/sy-picgo
Linux: ~/sy-picgo
```

原因：插件带有 `node_modules` 等大文件目录，如果放在思源笔记里面，笔记云同步的时候会导致非常缓慢，因此放在系统配置目录，避免进行同步。

**Comment by SkysCrystal** [comment]
> 重要变更：
> 
> 为了支持插件，将PicGO配置文件移动到系统配置目录，具体为
> 
> ```
> Mac: ~/Library/Application Support/sy-picgo
> Window: ~/AppData/Roaming/sy-picgo
> Linux: ~/sy-picgo
> ```
> 
> 原因：插件带有 `node_modules` 等大文件目录，如果放在思源笔记里面，笔记云同步的时候会导致非常缓慢，因此放在系统配置目录，避免进行同步。

请问是在思源笔记里卸载重装插件吗？

**Comment by terwer** [comment]
还没发布哦，耐心等待。。。
0.7.0预计过一段时间上线

**Comment by SkysCrystal** [comment]
明白啦，谢谢！不着急😆在 2023年2月9日，01:05，terwer ***@***.***> 写道：﻿
还没发布哦，耐心等待。。。
0.7.0预计过一段时间上线

**Comment by terwer** [comment]
事件监听已搞定，集成插件的步伐又向前迈进了一大步！

**Comment by terwer** [comment]
![Image](https://user-images.githubusercontent.com/3259282/219437422-f6941370-21ce-40cb-9cd7-51984f7088f1.png)


最新进度

1、插件列表、插件搜索 100%

2、插件安装环境配置 100%

3、插件设置右键菜单，菜单已显示，点击逻辑待处理 40%

**Comment by SkysCrystal** [comment]
大佬太强啦！
