### ISSUE TITLE
发布到Confluence

### ISSUE THREAD

**Issue by terwer** [terwer/src-sy-post-publisher#40]
配合适配器完美支持

发布到Confluence需要配合我的另一个适配器项目使用（强烈推荐），请参考：https://github.com/terwer/node-metaweblog-api-adaptor

**Comment by ocean-zhc** [comment]
在发布到 Confluence 时，确实需要配合另一个适配器项目使用，强烈推荐您参考 `node-metaweblog-api-adaptor` 项目。以下是具体的集成步骤：

1. **安装依赖**：
   确保您的环境中已安装 Node.js 和 npm。然后，在您的项目中运行以下命令以安装 `node-metaweblog-api-adaptor`：
   ```bash
   npm install node-metaweblog-api-adaptor
   ```

2. **配置适配器**：
   在您的项目中创建一个配置文件（例如 `config.json`），并添加必要的配置信息，如 Confluence 的 URL、用户名和密码等：
   ```json
   {
     "confluenceUrl": "https://your-confluence-instance.com",
     "username": "your-username",
     "password": "your-password"
   }
   ```

3. **初始化适配器**：
   在您的代码中引入并初始化适配器：
   ```javascript
   const adaptor = require('node-metaweblog-api-adaptor');
   const config = require('./config.json');

   const client = new adaptor(config);
   ```

4. **使用适配器发布内容**：
   使用适配器提供的 API 发布内容到 Confluence。例如，发布一个博客文章：
   ```javascript
   const post = {
     title: "您的文章标题",
     content: "您的文章内容",
     spaceKey: "您的空间键"
   };

   client.postPost(post, (err, result) => {
     if (err) {
       console.error("发布失败:", err);
     } else {
       console.log("发布成功:", result);
     }
   });
   ```

5. **测试和调试**：
   运行您的项目并测试适配器是否正常工作。根据需要调整配置和代码。

更多详细信息和示例代码，请参考适配器项目的 GitHub 页面：[node-metaweblog-api-adaptor](https://github.com/terwer/node-metaweblog-api-adaptor)。

希望这些步骤能帮助您顺利集成适配器并发布到 Confluence。如果有任何问题，请随时提问。
