### ISSUE TITLE
图床设置-PicGo设置中的时间戳重命名关闭后会自动打开的问题

### ISSUE THREAD

**Issue by ikcro** [terwer/src-sy-post-publisher#428]
目前最新版本

问题描述：

- 图床设置-PicGo设置中若是将默认的时间戳重命名设置为关闭状态后，每次发布时这个选项会自动设置为打开状态，也就是说PicGo设置中的 时间戳重命名这个功能的状态无法进行保存（设置完点击保存按钮只有本次生效，再次发布依然会自动设置为打开的状态）

**Comment by ikcro** [comment]
感觉问题出在了这里：
![iShot_2023-03-10_19 28 18](https://user-images.githubusercontent.com/8908528/224305780-5e07ca10-262a-4969-868d-62f7f05b5548.jpg)
在这个JavaScript代码中，form.autoRename = settings.autoRename || true语句的含义是将form.autoRename设置为settings.autoRename的值，如果settings.autoRename的值为假值（例如false、null、undefined、0、""等），则将其设置为true。

**Comment by terwer** [comment]
已修复。
这个其实是Node的语法糖问题没有更好的写法：

```
form.autoRename = settings.autoRename ?? true
```
