### ISSUE TITLE
阿里云OSS上传时携带了网址后缀

### ISSUE THREAD

**Issue by peterzh4ng** [terwer/src-sy-post-publisher#441]
阿里云OSS配置了网址后缀后，插件在上传图片时也会把后缀带上，导致上传的文件名非预期了：
![图片](https://user-images.githubusercontent.com/86906331/226071078-1c76fe03-4f8f-4f36-9bb4-9ec70f7da4b5.png)
![图片](https://user-images.githubusercontent.com/86906331/226071124-ca3ea53e-d647-4d37-abbf-bce01d6ee97d.png)

**Comment by terwer** [comment]
这个就是这样的，如果不带后缀，是无法进行处理的呀。
